apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-dados 
spec:
  acessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage:10Gi
  storageClassName: standard-rwo

# criado no gcp sem a necessidade de criar volume

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mmasao/projeto-database:1.0
        args: 
        - "--ignore-db-dir=lost+found" #ignora erro caso de erro no banco, resquicios de dados.
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql 
        
        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
          claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: php
  labels: 
    app: php
spec:
  repicas: 6
  selector: 
    mactchLabels:
      app: php
  template: 
    metadata:
      labels: 
        app: php
    spec: 
      containers: 
      - name: php
        image: mmasao/projeto-backend:1.0
        imagePullPolicy: Always
        ports:
        -containerPort: 80 